package com.springapp.controller;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.springapp.dto.EmployeeProjection;
import com.springapp.model.Employee;
import com.springapp.service.EmployeeService;

@RestController
@RequestMapping("/employees")
public class EmployeeController {

	@Autowired
	private EmployeeService service;

	// GET by id
	@GetMapping("/{empId}")
	public ResponseEntity<Employee> getById(@PathVariable String empId) {
		return ResponseEntity.ok(service.getById(empId));
	}

	// GET by name
	@GetMapping("/by-name")
	public ResponseEntity<List<Employee>> getByName(@RequestParam String name) {
		return ResponseEntity.ok(service.getByName(name));
	}

	// GET by department
	@GetMapping("/by-department")
	public ResponseEntity<List<Employee>> getByDepartment(@RequestParam String department) {
		return ResponseEntity.ok(service.getByDepartment(department));
	}

	// GET salary greater than
	@GetMapping("/salary-greater")
	public ResponseEntity<List<Employee>> salaryGreater(@RequestParam int minSalary) {
		return ResponseEntity.ok(service.getBySalaryGreaterThan(minSalary));
	}

	// GET by email
	@GetMapping("/by-email")
	public ResponseEntity<?> getByEmail(@RequestParam String email) {
		Optional<Employee> opt = service.getByEmail(email);
		return opt.<ResponseEntity<?>>map(ResponseEntity::ok)
				.orElseGet(() -> ResponseEntity.status(HttpStatus.NOT_FOUND).body("Not found"));
	}

	// Projection
	@GetMapping("/projection")
	public ResponseEntity<List<EmployeeProjection>> projectionByDept(@RequestParam String department) {
		return ResponseEntity.ok(service.fetchProjectionByDepartment(department));
	}

	// Native query example
	@GetMapping("/native/min-salary")
	public ResponseEntity<List<Employee>> nativeMinSalary(@RequestParam int minSalary) {
		return ResponseEntity.ok(service.fetchByMinSalaryNative(minSalary));
	}

	// Paging & sorting example:
	// /employees/paged?page=0&size=10&sort=salary,desc
	@GetMapping("/paged")
	public ResponseEntity<Page<Employee>> paged(@RequestParam(defaultValue = "0") int page,
			@RequestParam(defaultValue = "10") int size, @RequestParam(defaultValue = "empId,asc") String sort) {

		String[] sortParts = sort.split(",");
		Sort.Direction dir = Sort.Direction.fromString(sortParts[1]);
		Sort s = Sort.by(dir, sortParts[0]);
		Page<Employee> result = service.getAllPaged(page, size, s);
		return ResponseEntity.ok(result);
	}

	// Create
	@PostMapping
	public ResponseEntity<Employee> create(@RequestBody Employee emp) {
		// NOTE: If emp.empId is generated by DB and cannot be set, handle accordingly
		Employee saved = service.save(emp);
		return ResponseEntity.status(HttpStatus.CREATED).body(saved);
	}

	// Update full
	@PutMapping("/{empId}")
	public ResponseEntity<Employee> update(@PathVariable String empId, @RequestBody Employee emp) {
		// Ensure ID matches path
		emp.setEmpId(empId);
		Employee updated = service.save(emp);
		return ResponseEntity.ok(updated);
	}

	// Partial update: salary only (uses @Modifying update)
	@PatchMapping("/{empId}/salary")
	public ResponseEntity<String> updateSalary(@PathVariable String empId, @RequestParam int salary) {
		int rows = service.updateSalary(empId, salary);
		if (rows > 0)
			return ResponseEntity.ok("Salary updated");
		return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Employee not found");
	}

	// Delete
	@DeleteMapping("/{empId}")
	public ResponseEntity<Void> delete(@PathVariable String empId) {
		service.deleteById(empId);
		return ResponseEntity.noContent().build();
	}

	// Delete by email
	@DeleteMapping("/by-email")
	public ResponseEntity<Void> deleteByEmail(@RequestParam String email) {
		service.deleteByEmail(email);
		return ResponseEntity.noContent().build();
	}
}
